=== geogebra/geogebra/tools/xsd/ggb.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation>
This is a schema for file geogebra.xml which should be compatible with GeoGebra 4.0 file format.
</xs:documentation>
		<xs:appinfo>
This schema is a part of GeoGebra which is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or any later version.

This schema is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with GeoGebra; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
</xs:appinfo>
	</xs:annotation>
	<xs:include schemaLocation="common.xsd"/>
	<xs:element name="geogebra">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="gui"/>
				<xs:element ref="euclidianView" minOccurs="0" maxOccurs="2"/>
				<xs:element ref="euclidianView3D" minOccurs="0"/>
				<xs:element ref="spreadsheetView" minOccurs="0"/>
				<xs:element ref="keyboard" minOccurs="0"/>
				<xs:element ref="kernel"/>
				<xs:element ref="scripting" minOccurs="0"/>
				<xs:element ref="construction" minOccurs="0">
				<xs:annotation>
					<xs:documentation>
					This element is required except for the preferences file. 
					</xs:documentation>
				</xs:annotation>
				</xs:element>				
			</xs:sequence>
			<xs:attribute name="format" type="xs:double">
				<xs:annotation>
					<xs:documentation>
					Deprecated since 4.2, use version insted.
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="version" type="xs:string"/>
			<xs:attribute name="id" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="keyboard">
		<xs:complexType>
		<xs:attribute name="language" type="xs:string"/>
		<xs:attribute name="width" type="positiveInt"/>
		<xs:attribute name="height" type="positiveInt"/>
		<xs:attribute name="opacity" type="xs:double"/>
		<xs:attribute name="show" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="scripting">
		<xs:complexType>
		<xs:attribute name="language" type="xs:string"/>
		<xs:attribute name="disabled" type="xs:boolean"/>
		<xs:attribute name="blocked" type="xs:boolean"/>		
		</xs:complexType>
	</xs:element>
	
	<xs:element name="gui">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element name="window" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="width" type="positiveInt" use="required"/>
						<xs:attribute name="height" type="positiveInt" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="perspectives" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="perspective" maxOccurs="unbounded" minOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="settings">
					<xs:complexType>
						<xs:attribute name="ignoreDocument" type="xs:boolean"/>
						<xs:attribute name="showTitleBar" type="xs:boolean"/>
						<xs:attribute name="allowStyleBar" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>				
				<xs:element name="labelingStyle" type="intVal" minOccurs="0"/>
				<xs:element name="mouse">
					<xs:complexType>
						<xs:attribute name="reverseWheel" type="xs:boolean"/>						
					</xs:complexType>
				</xs:element>
				<xs:element name="consProtColumns" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="col0" type="xs:boolean"/>
						<xs:attribute name="col1" type="xs:boolean"/>
						<xs:attribute name="col2" type="xs:boolean"/>
						<xs:attribute name="col3" type="xs:boolean"/>
						<xs:attribute name="col4" type="xs:boolean"/>
						<xs:attribute name="col5" type="xs:boolean"/>
						<xs:attribute name="col6" type="xs:boolean"/>
						<xs:attribute name="col7" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="consProtocol" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="useColors" type="xs:boolean"/>
						<xs:attribute name="addIcons" type="xs:boolean"/>
						<xs:attribute name="showOnlyBreakpoints" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="consProtNavigationBar" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="show" type="xs:boolean"/>
						<xs:attribute name="playButton" type="xs:boolean"/>
						<xs:attribute name="playDelay" type="xs:double"/>
						<xs:attribute name="protButton" type="xs:boolean"/>
						<xs:attribute name="consStep" type="xs:int"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="show" minOccurs="0"/>
				
				<xs:element ref="splitDivider" minOccurs="0"/>
				
				<xs:element ref="toolbar" minOccurs="0"/>
				
				<xs:element name="font" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="size" type="positiveInt" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="menuFont" minOccurs="0">
					<xs:complexType>
					<xs:annotation>
					<xs:documentation>
					size=-1 means that we use the same font for graphics and menus
					</xs:documentation>
					</xs:annotation>
						<xs:attribute name="size" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="tooltipSettings" minOccurs="0">
					<xs:complexType>
					<xs:annotation>
					<xs:documentation>
					timeout=-1 means that we don't want to display them
					</xs:documentation>
					</xs:annotation>
						<xs:attribute name="timeout" type="xs:int"/>
						<xs:attribute name="language" type="xs:string"/>
					</xs:complexType>
				</xs:element>				
				<xs:element name="graphicsSettings">
					<xs:complexType>
						<xs:attribute name="javaLatexFonts" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>            
			</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="show">
		<xs:annotation>
			<xs:documentation>
				Deprecated since 4.0, use perspectives insted.
				</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="algebraView" type="xs:boolean" />
			<xs:attribute name="spreadsheetView" type="xs:boolean" />
			<xs:attribute name="auxiliaryObjects" type="xs:boolean" />
			<xs:attribute name="algebraInput" type="xs:boolean" />
			<xs:attribute name="cmdList" type="xs:boolean" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="splitDivider">
		<xs:annotation>
			<xs:documentation>
				Deprecated since 4.0, use perspectives/perspective/panes insted.
				</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="loc" type="nonNegInt"/>
			<xs:attribute name="locVertical" type="nonNegInt"/>
			<xs:attribute name="loc2" type="positiveInt"/>
			<xs:attribute name="locVertical2" type="nonNegInt"/>
			<xs:attribute name="horizontal" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="toolbar">
		<xs:annotation>
			<xs:documentation>
				Deprecated since 4.0, use perspectives/perspective/toolbar  insted.
				</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="str" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="toolbar">
		<xs:attribute name="help" type="xs:boolean"/>
		<xs:attribute name="show" type="xs:boolean"/>
		<xs:attribute name="items" type="xs:string"/>
		<xs:attribute name="position" type="nonNegInt"/>
	</xs:complexType>
	
	<xs:element name="perspective">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="panes">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="pane" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="views">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="view" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="toolbar" type="toolbar"/>
				<xs:element name="show" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="axes" type="xs:boolean"/>
						<xs:attribute name="grid" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="input">
					<xs:complexType>
						<xs:attribute name="show" type="xs:boolean"/>
						<xs:attribute name="cmd" type="xs:boolean"/>
						<xs:attribute name="top" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>
			
				<xs:element name="dockBar" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="show" type="xs:boolean"/>
						<xs:attribute name="east" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="pane">
		<xs:complexType>
			<xs:attribute name="location" type="xs:string" use="required"/>
			<xs:attribute name="divider" type="javaDouble"/>
			<xs:attribute name="orientation" type="nonNegInt" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="view">
		<xs:complexType>
			<xs:attribute name="id" type="positiveInt" use="required"/>
			<xs:attribute name="toolbar" type="xs:string"/>
			<xs:attribute name="visible" type="xs:boolean"/>
			<xs:attribute name="inframe" type="xs:boolean"/>
			<xs:attribute name="stylebar" type="xs:boolean"/>
			<xs:attribute name="location" type="xs:string"/>
			<xs:attribute name="size" type="nonNegInt"/>
			<xs:attribute name="window" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="size">
		<xs:complexType>
			<xs:attribute name="width" type="nonNegInt" use="required"/>
			<xs:attribute name="height" type="nonNegInt" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="spreadsheetView">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="size"/>
				<xs:element name="prefCellSize" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="width" type="xs:int"/>
						<xs:attribute name="height" type="xs:int"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="spreadsheetColumn" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="id" type="nonNegInt" use="required"/>
						<xs:attribute name="width" type="positiveInt" use="required"/>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="selection" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="hScroll" type="xs:integer"/>
						<xs:attribute name="vScroll" type="xs:integer"/>
						<xs:attribute name="column" type="xs:integer"/>
						<xs:attribute name="row" type="xs:integer"/>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="layout" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="showGrid" type="xs:boolean"/>
						<xs:attribute name="showFormulaBar" type="xs:boolean"/>
						<xs:attribute name="showHScrollBar" type="xs:boolean"/>
						<xs:attribute name="showVScrollBar" type="xs:boolean"/>
						<xs:attribute name="showBrowserPanel" type="xs:boolean"/>
						<xs:attribute name="showColumnHeader" type="xs:boolean"/>
						<xs:attribute name="showRowHeader" type="xs:boolean"/>
						<xs:attribute name="allowSpecialEditor" type="xs:boolean"/>
						<xs:attribute name="allowToolTips" type="xs:boolean"/>
						<xs:attribute name="equalsRequired" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="spreadsheetCellFormat" minOccurs="0">
				<xs:complexType>
				<xs:attribute name="formatMap" type="xs:string"/>
				</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="euclidianView">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="viewNumber" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="viewNo" type="positiveInt"/>
					</xs:complexType>
				</xs:element>
				<!-- TODO: check whether we can't have size in test app -->
				<xs:element ref="size" minOccurs="0"/>
				<xs:element name="coordSystem">
					<xs:complexType>
						<xs:attribute name="xZero" type="xs:double"/>
						<xs:attribute name="yZero" type="xs:double"/>
						<xs:attribute name="scale" type="xs:double"/>
						<xs:attribute name="xscale" type="xs:double"/>
						<xs:attribute name="yscale" type="xs:double"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="evSettings">
					<xs:complexType>
						<xs:attribute name="axes" type="xs:boolean"/>
						<xs:attribute name="grid" type="xs:boolean"/>
						<xs:attribute name="gridIsBold" type="xs:boolean"/>
						<xs:attribute name="pointCapturing" type="pointCapturings"/>
						<xs:attribute name="pointStyle" type="pointStyles"/>
						<xs:attribute name="rightAngleStyle" type="rightAngleStyles"/>
						<xs:attribute name="checkboxSize" type="nonNegInt"/>
						<xs:attribute name="gridType" type="gridTypes"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="bgColor" type="rgbColor"/>
				<xs:element name="axesColor" type="rgbColor"/>
				<xs:element name="gridColor" type="rgbColor"/>
				
				<xs:element name="lineStyle">
					<xs:complexType>
						<xs:attribute name="axes" type="axisTypes"/>
						<xs:attribute name="grid" type="lineTypes"/>
					</xs:complexType>
				</xs:element>
				
				<xs:element ref="axis" minOccurs="2" maxOccurs="2"/>
				<xs:element name="grid" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="distX" type="xs:double"/>
						<xs:attribute name="distY" type="xs:double"/>
						<xs:attribute name="distTheta" type="xs:double"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="euclidianView3D">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="size" minOccurs="0"/><!-- does it really occur? -->
				<xs:element name="coordSystem">
					<xs:complexType>
						<xs:attribute name="xZero" type="xs:double"/>
						<xs:attribute name="yZero" type="xs:double"/>
						<xs:attribute name="zZero" type="xs:double"/>
						<xs:attribute name="scale" type="xs:double"/>
						<xs:attribute name="xAngle" type="xs:double"/>
						<xs:attribute name="zAngle" type="xs:double"/>
					</xs:complexType>
				</xs:element>
				
				<xs:element ref="axis" minOccurs="3" maxOccurs="3"/>
				<xs:element name="plate">
					<xs:complexType>
						<xs:attribute name="show" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="grid">
					<xs:complexType>
						<xs:attribute name="show" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="clipping">
					<xs:complexType>
						<xs:attribute name="use" type="xs:boolean"/>
						<xs:attribute name="show" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	
	<xs:element name="axis">
		<xs:complexType>
			<xs:attribute name="id" type="axisIds" use="required"/>
			<xs:attribute name="show" type="xs:boolean"/>
			<xs:attribute name="label" type="xs:string"/>
			<xs:attribute name="unitLabel" type="xs:string"/>
			<xs:attribute name="tickStyle" type="tickStyles"/>
			<xs:attribute name="tickDistance" type="xs:double"/>
			<xs:attribute name="axisCross" type="xs:double"/>
			<xs:attribute name="positiveAxis" type="xs:boolean"/>
			<xs:attribute name="showNumbers" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="kernel">
		<xs:complexType>
			<xs:all minOccurs="0">
				<xs:element name="continuous" type="boolVal" minOccurs="0"/>
				<xs:element name="usePathAndRegionParameters" type="stringVal" minOccurs="0"/>
				<xs:element name="decimals" type="intVal"/>
				<xs:element name="significantFigures" type="intVal" minOccurs="0"/>
				<xs:element name="angleUnit">
					<xs:complexType>
						<xs:attribute name="val" type="angleUnits" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="algebraStyle" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="val" type="algebraStyles" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="coordStyle" type="intVal"/>
				<xs:element name="startAnimation" type="boolVal" minOccurs="0"/>
				<xs:element name="angleFromInvTrig" type="boolVal" minOccurs="0"/>
            
				<xs:element name="localization" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="digits" type="xs:boolean"/>
						<xs:attribute name="labels" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="casSettings" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="timeout" type="xs:double"/>
						<xs:attribute name="expRoots" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	
	
</xs:schema>

=== geogebra/geogebra/common/src/geogebra/common/main/xml/default-preferences.xml
<?xml version="1.0" encoding="utf-8"?>
<geogebra format="4.0" xsi:noNamespaceSchemaLocation="http://www.geogebra.org/ggb.xsd" xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
<gui>
	<window width="800" height="600" />
	<settings ignoreDocument="false" showTitleBar="true" />
	<labelingStyle  val="0"/>
	<mouse reverseWheel="true"/>
	<font  size="12"/>
	<menuFont size="-1"/>
	<tooltipSettings language="" timeout="0"/>
	<graphicsSettings javaLatexFonts="false"/>
</gui>
<euclidianView>
	<size  width="640" height="480"/>
	<coordSystem xZero="215.0" yZero="315.0" scale="50.0" yscale="50.0"/>
	<evSettings axes="true" grid="false" gridIsBold="false" pointCapturing="3" rightAngleStyle="2" checkboxSize="13" gridType="0"/>
	<bgColor r="255" g="255" b="255"/>
	<axesColor r="0" g="0" b="0"/>
	<gridColor r="192" g="192" b="192"/>
	<lineStyle axes="1" grid="10"/>
	<axis id="0" show="true" label="" unitLabel="" tickStyle="1" showNumbers="true" axisCross="0.0" positiveAxis="false"/>
	<axis id="1" show="true" label="" unitLabel="" tickStyle="1" showNumbers="true" axisCross="0.0" positiveAxis="false"/>
</euclidianView>
<kernel>
	<continuous val="false"/>
	<decimals val="2"/>
	<angleUnit val="degree"/>
	<algebraStyle val="0"/>
	<coordStyle val="0"/>
	<localization digits="false" labels="true"/>
	<angleFromInvTrig val="false"/>
	<casSettings timeout="5" expRoots="true"/>
</kernel>
<scripting blocked="false"/>
</geogebra>
